- path: /jcc-threats-:date.svg
  model: svg
  blob: blob
  headers:
    Content-Type: image/svg+xml

- path: /jcc-threats-:date.js
  model: jcc-threats
  template: jcc-threats.js
  headers:
    Content-Type: application/javascript; charset=utf-8

- path: /jcc-threats.js
  model: jcc-threats
  template: jcc-threats.js
  headers:
    Content-Type: application/javascript; charset=utf-8

- path: /test/jcc-threats
  model: jcc-threats
  template: test/jcc-threats
